### PR TITLE
fileutils: Use ModeType as the mask for mode checks

### PR DESCRIPTION
**Pull request by wking**
POSIX provides [`S_IS*(m)` macros][2] to portably interpret the mode type, but does not define values for each type.  @alban [pointed out][1] that `st_mode` is not a bitfield on Linux [1].  For example, [Linux defines][3]:

    S_IFBLK 060000
    S_IFDIR 040000
    S_IFCHR 020000

So `m&S_IFCHR == S_IFCHR`, for example, would succeed for both character and block devices.  Go translates the system values to [a platform-agnostic bitfield][4], so the previous approach works on Go.  But it may be confusing for people used to the native non-bitfield mode, so this pull request moves us to an approach that does not rely on Go's using a bitfield.

[1]: https://github.com/opencontainers/runtime-tools/pull/308#discussion_r179799657
[2]: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_stat.h.html
[3]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/stat.h?h=v4.16#n9
[4]: https://github.com/golang/go/blob/b0d437f866eb8987cde7e6550cacd77876f36d4b/src/os/types.go#L45

### CODE REVIEW

**Comment by wking** [comment]
Hang on, I'm going to drop some of these `syscall` constants too…

**Comment by wking** [comment]
> Hang on, I'm going to drop some of these syscall constants too…

Ok, I've pushed that along a bit with e48df7f → 8bad3ca.  Let me know if you like that as it stands, or if you'd like me to restore some of the `syscall` constants, or if you'd like me to push further to drop `syscall` entirely in favor of `x/sys/unix`.

**Comment by thaJeztah** [comment]
@mrunalp PTAL

**Comment by mrunalp** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks! Do you think it's worth considering tagging a `v1.0.0` release for this repository? It looks like it's been in use for quite a while by runc, and no considerable changes during that time

**Comment by kolyshkin** [comment]
> It looks like it's been in use for quite a while by runc, and no considerable changes during that time

In case there are no users except runc, I'd rather merge this one to runc. Easier to maintain that way.

**Comment by thaJeztah** [comment]
@kolyshkin this might help checking who uses it; https://grep.app/search?q=%22github.com/mrunalp/fileutils%22&filter[lang][0]=Go

**Pull request merged**
